#!/bin/bash

set -v

export PROMOTE_FROM=$1

export BOOKING_IMAGE=$BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-${PROMOTE_FROM}
export POSTGRES_IMAGE=$POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-${PROMOTE_FROM}

echo "Pomoting images - $BOOKING_IMAGE $POSTGRES_IMAGE"

docker -v login -u gitlab-ci-token -p $GITLAB_REGISTRY_PASSWORD registry.gitlab.com

docker pull $BOOKING_IMAGE
docker pull $POSTGRES_IMAGE
docker tag $POSTGRES_IMAGE $POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG
docker tag $BOOKING_IMAGE $BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG
docker push $BOOKING_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG
docker push $POSTGRES_IMAGE_NAME:$CI_COMMIT_SHA-$CI_ENVIRONMENT_SLUG

set +v

